archi_name: scandium_weather
data.use_weather: true
model:
  s1_ae_config:  # U-Net-like architecture
    in_dim: 2  # always 2 (if input={VV, VH})
    out_dim: 1
    layer_channels: [16, 32, 64]
    conv_per_layer: 1
    residual: false
    dropout_rate: 0.0
  mask_module_dim: [6, 2]  # include input dim
  glob_module_dims: [57, 128, 57]  # include input dim
  conv_block_dims: [32, 64, 128]  # exclude input dim (automatically inferred)
