archi_name: strontium
model:
  sodium_config:
    pretrained: false
    run_id: 0
    ae_config:  # U-Net-like architecture
      in_dim: 11  # 6 + 2*mask_embedding_channels + mlp_layers[-1]
      out_dim: 1
      layer_channels: [32, 64, 128]
      conv_per_layer: 2
      residual: true
      dropout_rate: 0.0
    mask_embedding_channels: 2
    mlp_layers: [2, 1]
  aluminium_config:
    pretrained: false
    run_id: 0
    ae_config:  # U-Net-like architecture
      in_dim: 7  # 2 + 2*mask_emb + mlp_layers[-1]
      out_dim: 1
      layer_channels: [32, 64, 128]
      conv_per_layer: 2
      residual: true
      dropout_rate: 0.0
    mask_embedding_channels: 2
    mlp_layers: [2, 1]
  ae_config:
    in_dim: 64 # aluminium_config['layer_channels'][0] + sodium_config['layer_channels'][0]
    out_dim: 1
    layer_channels: [64, 128, 256]
    conv_per_layer: 2
    residual: true
    dropout_rate: 0.0

train:
  weight_2: 0.1
  weight_3: 0.15

dataloader.batch_size: 8
