archi_name: vanadium
model:
  s1_ae_config:  # U-Net-like architecture
    in_dim: 2  # always 2 (if input={VV, VH})
    out_dim: 1
    layer_channels: [16, 32, 64]
    conv_per_layer: 1
    residual: false
    dropout_rate: 0.0
  mask_module_dim: [6, 2]  # include input dim
  glob_module_dims: [2, 8, 2]  # include input dim
  segformer_config:
    num_encoder_blocks: 3
    strides: [2, 2, 2]
    hidden_sizes: [32, 64, 128]
    num_attention_heads: [1, 2, 4]
    hidden_dropout_prob: 0.0
    attention_probs_dropout_prob: 0.0
  transposed_conv_block_dims: [64, 32, 16]
