data:
  dataset_path: '../data'
  csv_name: 'train_regular.csv'
  csv_grid_name: 'train_regular_grids.csv'
  grid_augmentation: false
dataloader:
  num_workers: 6
  batch_size: 16
  shuffle: true
  prefetch_factor: 2
model:
  s1_ae_config:  # U-Net-like architecture
    in_dim: 2  # always 2 (if input={VV, VH})
    out_dim: 1
    layer_channels: [16, 32, 64]
    conv_per_layer: 1
    residual: false
    dropout_rate: 0.0
  mask_module_dim: [6, 2]  # include input dim
  glob_module_dims: [2, 8, 2]  # include input dim
  segformer_config:
    num_encoder_blocks: 4
    strides: [2, 2, 2, 1]
    hidden_sizes: [32, 64, 128, 128]
    num_attention_heads: [1, 2, 4, 4]
    hidden_dropout_prob: 0.0
    attention_probs_dropout_prob: 0.0
  transposed_conv_block_dims: [64, 32, 16]
train:
  learning_rate: 0.001
  learning_rate_n_mult: 2  # number of times to decay lr (evenly spaced during the full training)
  learning_rate_decay: 0.2  # lr *= decay at each decay step
  n_epochs: 30
  log_interval: 20  # in iterations
  save_interval: 10  # in epochs
  interm_supervis: false  # intermediate supervision for AE
