data:
  dataset_path: '../data'
  csv_name: 'train_regular.csv'
  csv_grid_name: 'train_regular_grids.csv'
  grid_augmentation: false
dataloader:
  num_workers: 6
  batch_size: 16
  shuffle: true
  prefetch_factor: 2
model:
  ae_config:  # U-Net-like architecture
    in_dim: 6  # always 2 (if input={VV, VH})
    out_dim: 1
    layer_channels: [32, 64, 128]
    conv_per_layer: 2
    residual: true
    dropout_rate: 0.0
train:
  learning_rate: 0.001
  learning_rate_n_mult: 2  # number of times to decay lr (evenly spaced during the full training)
  learning_rate_decay: 0.2  # lr *= decay at each decay step
  n_epochs: 30
  log_interval: 20  # in iterations
  save_interval: 5  # in epochs
  interm_supervis: false  # intermediate supervision for AE
